name: the_brand
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^6.3.0
  built_collection: ^4.1.0
  analyzer: ^0.33.3
  flutter_redux: ^0.5.3 
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.3
  built_value_generator: ^6.2.0
  


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/c1.jpg
    - assets/images/m1.jpeg
    - assets/images/m2.jpg
    - assets/images/w1.jpeg
    - assets/images/w3.jpeg
    - assets/images/w4.jpeg

    - assets/images/cats/accessories.png
    - assets/images/cats/dress.png
    - assets/images/cats/formal.png
    - assets/images/cats/informal.png
    - assets/images/cats/jeans.png
    - assets/images/cats/shoe.png
    - assets/images/cats/tshirt.png

    - assets/images/products/blazer1.jpeg
    - assets/images/products/blazer2.jpeg
    - assets/images/products/dress1.jpeg
    - assets/images/products/dress2.jpeg
    - assets/images/products/hills1.jpeg
    - assets/images/products/hills2.jpeg
    - assets/images/products/pants1.jpg
    - assets/images/products/pants2.jpeg
    - assets/images/products/shoe1.jpg
    - assets/images/products/skt1.jpeg
    - assets/images/products/skt2.jpeg

    - assets/images/firstcard/HOME-APPLIANCES-2.PNG
    - assets/images/firstcard/services-png-7.png
    - assets/images/firstcard/Food-PNG-High-Quality-Image.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
